### ISSUE TITLE
Cannot login with pixiv

### ISSUE THREAD

**Issue by MidnightKittenCat** [EngMarchG/Fsg-Pp#2]
Logging in...
Traceback (most recent call last):
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\Fsg_pp.py", line 17, in pix_imgs
    imgz = getOrderedPixivImages(driver=driver, exec_path=exec_path, user_search=searchQuery, num_pics=num_pics, num_pages=num_pages,searchTypes=searchTypes,viewRestriction=viewRestriction,imageControl=imageControl, n_likes=n_likes, n_bookmarks=n_bookmarks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\sites\pixiv.py", line 83, in getOrderedPixivImages
    searchQuery(user_search, driver, search_param["bar_search"], isLoggedIn=success_login)
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\commands\universal.py", line 17, in searchQuery
    WebDriverWait(driver, timeout=15).until(EC.presence_of_element_located((By.XPATH, elem)))
  File "C:\Users\midnight\Documents\downloadsvpn29392\Fsg_Pp-1.0.0\Fsg_Pp-1.0.0\venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x003B8893+48451]
        (No symbol) [0x0034B8A1]
        (No symbol) [0x00255058]
        (No symbol) [0x00280467]
        (No symbol) [0x0028069B]
        (No symbol) [0x002ADD92]
        (No symbol) [0x0029A304]
        (No symbol) [0x002AC482]
        (No symbol) [0x0029A0B6]
        (No symbol) [0x00277E08]
        (No symbol) [0x00278F2D]
        GetHandleVerifier [0x00618E3A+2540266]
        GetHandleVerifier [0x00658959+2801161]
        GetHandleVerifier [0x0065295C+2776588]
        GetHandleVerifier [0x00442280+612144]
        (No symbol) [0x00354F6C]
        (No symbol) [0x003511D8]
        (No symbol) [0x003512BB]
        (No symbol) [0x00344857]
        BaseThreadInitThunk [0x770800C9+25]
        RtlGetAppContainerNamedObjectPath [0x773A7B4E+286]
        RtlGetAppContainerNamedObjectPath [0x773A7B1E+238]

**Comment by EngMarchG** [comment]
We are aware of the issue and have made slight modifications to prevent it from failing directly. However, the issue is caused by the slow loading of the Pixiv page and the latency of your network connection to the server.
