### ISSUE TITLE
Tried using the preview version and errors

### ISSUE THREAD

**Issue by MidnightKittenCat** [EngMarchG/Fsg-Pp#6]
`Traceback (most recent call last):
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\Fsg_pp.py", line 16, in pix_imgs
    driver = driver_instance.create_driver(profile=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\commands\driver_instance.py", line 38, in create_driver
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 117
Current browser version is 119.0.6045.160 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
        GetHandleVerifier [0x00007FF7F8367892+54818]
        (No symbol) [0x00007FF7F82D6AC2]
        (No symbol) [0x00007FF7F818DA3B]
        (No symbol) [0x00007FF7F81C0972]
        (No symbol) [0x00007FF7F81BFDCE]
        (No symbol) [0x00007FF7F81BAA4B]
        (No symbol) [0x00007FF7F81B802E]
        (No symbol) [0x00007FF7F81F67FB]
        (No symbol) [0x00007FF7F81EE883]
        (No symbol) [0x00007FF7F81C3691]
        (No symbol) [0x00007FF7F81C48D4]
        GetHandleVerifier [0x00007FF7F86CB992+3610402]
        GetHandleVerifier [0x00007FF7F8721860+3962352]
        GetHandleVerifier [0x00007FF7F8719D4F+3930847]
        GetHandleVerifier [0x00007FF7F8403646+693206]
        (No symbol) [0x00007FF7F82E1628]
        (No symbol) [0x00007FF7F82DD934]
        (No symbol) [0x00007FF7F82DDA62]
        (No symbol) [0x00007FF7F82CE113]
        BaseThreadInitThunk [0x00007FF9F4D3257D+29]
        RtlUserThreadStart [0x00007FF9F57CAA58+40]

Traceback (most recent call last):
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\Fsg_pp.py", line 16, in pix_imgs
    driver = driver_instance.create_driver(profile=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\commands\driver_instance.py", line 38, in create_driver
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 117
Current browser version is 119.0.6045.160 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
        GetHandleVerifier [0x00007FF7F8367892+54818]
        (No symbol) [0x00007FF7F82D6AC2]
        (No symbol) [0x00007FF7F818DA3B]
        (No symbol) [0x00007FF7F81C0972]
        (No symbol) [0x00007FF7F81BFDCE]
        (No symbol) [0x00007FF7F81BAA4B]
        (No symbol) [0x00007FF7F81B802E]
        (No symbol) [0x00007FF7F81F67FB]
        (No symbol) [0x00007FF7F81EE883]
        (No symbol) [0x00007FF7F81C3691]
        (No symbol) [0x00007FF7F81C48D4]
        GetHandleVerifier [0x00007FF7F86CB992+3610402]
        GetHandleVerifier [0x00007FF7F8721860+3962352]
        GetHandleVerifier [0x00007FF7F8719D4F+3930847]
        GetHandleVerifier [0x00007FF7F8403646+693206]
        (No symbol) [0x00007FF7F82E1628]
        (No symbol) [0x00007FF7F82DD934]
        (No symbol) [0x00007FF7F82DDA62]
        (No symbol) [0x00007FF7F82CE113]
        BaseThreadInitThunk [0x00007FF9F4D3257D+29]
        RtlUserThreadStart [0x00007FF9F57CAA58+40]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Documents\AI Projects\Pfp finder\venv\Lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None`

**Comment by WootaMelon** [comment]
Hello, The issue is in this line: 

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: **This version of ChromeDriver only supports Chrome version 117**
**Current browser version is 119.0.6045.160 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe**

Your selenium chrome driver needs to be updated since it's still on 117 and your current browser version is on 119. This will prevent it from being able to download images. 

Did you try re-installing a fresh venv/updating selenium and gradio? Both updated with some code breaking changes so it's advised to either update them or re-run the installation.bat and remove your existing old venv folder with a new one.

Do let us know if it worked out or if you are still getting errors, thanks!

**Comment by MidnightKittenCat** [comment]
Seems to of worked, thanks!
